apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: prometheus
  namespace: istio-gateway
spec:
  host: prometheus-istio-gateway.apps-crc.testing
  to:
    kind: Service
    name: ingressgateway
  port:
    targetPort: http2
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana
  namespace: istio-gateway
spec:
  host: grafana-istio-gateway.apps-crc.testing
  to:
    kind: Service
    name: ingressgateway
  port:
    targetPort: http2
