services:
  details-api:
    image: sixeyed/examples-bookinfo-details-v1:1.18.0
    build:
      context: details-api

  productpage:
    image: sixeyed/examples-bookinfo-productpage-v1:1.18.0
    build:
      context: productpage
