apiVersion: sailoperator.io/v1
kind: Istio
metadata:
  name: default
  namespace: istio-system
spec:
  namespace: istio-system
  version: v1.24-latest
  values:
    meshConfig:
      defaultProviders:
        metrics:
        - prometheus
        tracing:
        - jaeger-zipkin
      enableTracing: true
      extensionProviders:
      - name: jaeger-zipkin
        zipkin:
          service: jaeger-collector.openshift-distributed-tracing.svc.cluster.local
          port: 9411
          maxTagLength: 56
      enablePrometheusMerge: true
      rootNamespace: istio-system
      trustDomain: cluster.local
      accessLogFile: /dev/stdout
      accessLogEncoding: JSON
